var concepts =
[
    [ "vctr", "namespacevctr.html", [
      [ "are", null, [
        [ "noExpressionTemplates", "conceptvctr_1_1are_1_1noExpressionTemplates.html", null ],
        [ "same", "conceptvctr_1_1are_1_1same.html", null ]
      ] ],
      [ "has", null, [
        [ "prepareNeonEvaluation", "conceptvctr_1_1has_1_1prepareNeonEvaluation.html", null ],
        [ "getNeon", "conceptvctr_1_1has_1_1getNeon.html", null ],
        [ "prepareAVXEvaluation", "conceptvctr_1_1has_1_1prepareAVXEvaluation.html", null ],
        [ "getAVX", "conceptvctr_1_1has_1_1getAVX.html", null ],
        [ "prepareSSEEvaluation", "conceptvctr_1_1has_1_1prepareSSEEvaluation.html", null ],
        [ "getSSE", "conceptvctr_1_1has_1_1getSSE.html", null ],
        [ "indexOperator", "conceptvctr_1_1has_1_1indexOperator.html", null ],
        [ "constIndexOperator", "conceptvctr_1_1has_1_1constIndexOperator.html", null ],
        [ "evalNextVectorOpInExpressionChain", "conceptvctr_1_1has_1_1evalNextVectorOpInExpressionChain.html", null ],
        [ "reduceElementWise", "conceptvctr_1_1has_1_1reduceElementWise.html", null ],
        [ "reduceVectorOp", "conceptvctr_1_1has_1_1reduceVectorOp.html", null ],
        [ "reduceNeonRegisterWise", "conceptvctr_1_1has_1_1reduceNeonRegisterWise.html", null ],
        [ "reduceAVXRegisterWise", "conceptvctr_1_1has_1_1reduceAVXRegisterWise.html", null ],
        [ "reduceSSERegisterWise", "conceptvctr_1_1has_1_1reduceSSERegisterWise.html", null ],
        [ "data", "conceptvctr_1_1has_1_1data.html", null ],
        [ "dataWithElementType", "conceptvctr_1_1has_1_1dataWithElementType.html", null ],
        [ "size", "conceptvctr_1_1has_1_1size.html", null ],
        [ "sizeAndData", "conceptvctr_1_1has_1_1sizeAndData.html", null ],
        [ "sizeAndDataWithElementType", "conceptvctr_1_1has_1_1sizeAndDataWithElementType.html", null ],
        [ "begin", "conceptvctr_1_1has_1_1begin.html", null ],
        [ "end", "conceptvctr_1_1has_1_1end.html", null ],
        [ "resize", "conceptvctr_1_1has_1_1resize.html", null ],
        [ "getStorageInfo", "conceptvctr_1_1has_1_1getStorageInfo.html", null ],
        [ "isNotAliased", "conceptvctr_1_1has_1_1isNotAliased.html", null ],
        [ "iterateOverRuntimeArgChain", "conceptvctr_1_1has_1_1iterateOverRuntimeArgChain.html", null ],
        [ "applyRuntimeArgs", "conceptvctr_1_1has_1_1applyRuntimeArgs.html", null ],
        [ "operatorPlusEquals", "conceptvctr_1_1has_1_1operatorPlusEquals.html", null ],
        [ "init", "conceptvctr_1_1has_1_1init.html", null ],
        [ "getStart", "conceptvctr_1_1has_1_1getStart.html", null ],
        [ "getLength", "conceptvctr_1_1has_1_1getLength.html", null ],
        [ "getEnd", "conceptvctr_1_1has_1_1getEnd.html", null ],
        [ "getStartWithValueType", "conceptvctr_1_1has_1_1getStartWithValueType.html", null ],
        [ "getLengthWithValueType", "conceptvctr_1_1has_1_1getLengthWithValueType.html", null ],
        [ "getEndWithValueType", "conceptvctr_1_1has_1_1getEndWithValueType.html", null ]
      ] ],
      [ "is", null, [
        [ "constexprStorageInfo", "conceptvctr_1_1is_1_1constexprStorageInfo.html", null ],
        [ "anyVctr", "conceptvctr_1_1is_1_1anyVctr.html", null ],
        [ "anyVctrWithValueType", "conceptvctr_1_1is_1_1anyVctrWithValueType.html", null ],
        [ "expression", "conceptvctr_1_1is_1_1expression.html", null ],
        [ "expressionWithValueType", "conceptvctr_1_1is_1_1expressionWithValueType.html", null ],
        [ "expressionChainBuilder", "conceptvctr_1_1is_1_1expressionChainBuilder.html", null ],
        [ "anyVctrOrExpression", "conceptvctr_1_1is_1_1anyVctrOrExpression.html", null ],
        [ "stdArray", "conceptvctr_1_1is_1_1stdArray.html", null ],
        [ "stdSpan", "conceptvctr_1_1is_1_1stdSpan.html", null ],
        [ "view", "conceptvctr_1_1is_1_1view.html", null ],
        [ "expressionWithEvalVectorOp", "conceptvctr_1_1is_1_1expressionWithEvalVectorOp.html", null ],
        [ "suitableForAccelerateSSEOp", "conceptvctr_1_1is_1_1suitableForAccelerateSSEOp.html", null ],
        [ "suitableForAccelerateNeonOp", "conceptvctr_1_1is_1_1suitableForAccelerateNeonOp.html", null ],
        [ "suitableForAccelerateRealFloatVectorOp", "conceptvctr_1_1is_1_1suitableForAccelerateRealFloatVectorOp.html", null ],
        [ "suitableForAccelerateComplexFloatVectorOp", "conceptvctr_1_1is_1_1suitableForAccelerateComplexFloatVectorOp.html", null ],
        [ "suitableForAccelerateRealOrComplexFloatVectorOp", "conceptvctr_1_1is_1_1suitableForAccelerateRealOrComplexFloatVectorOp.html", null ],
        [ "suitableForAccelerateComplexToRealFloatVectorOp", "conceptvctr_1_1is_1_1suitableForAccelerateComplexToRealFloatVectorOp.html", null ],
        [ "suitableForAccelerateRealIntToFloatVectorOp", "conceptvctr_1_1is_1_1suitableForAccelerateRealIntToFloatVectorOp.html", null ],
        [ "suitableForAccelerateRealFloatVectorReductionOp", "conceptvctr_1_1is_1_1suitableForAccelerateRealFloatVectorReductionOp.html", null ],
        [ "suitableForIppRealFloatVectorOp", "conceptvctr_1_1is_1_1suitableForIppRealFloatVectorOp.html", null ],
        [ "suitableForIppRealSingedInt32VectorOp", "conceptvctr_1_1is_1_1suitableForIppRealSingedInt32VectorOp.html", null ],
        [ "suitableForIppComplexFloatVectorOp", "conceptvctr_1_1is_1_1suitableForIppComplexFloatVectorOp.html", null ],
        [ "suitableForIppRealOrComplexFloatVectorOp", "conceptvctr_1_1is_1_1suitableForIppRealOrComplexFloatVectorOp.html", null ],
        [ "suitableForIppComplexToRealFloatVectorOp", "conceptvctr_1_1is_1_1suitableForIppComplexToRealFloatVectorOp.html", null ],
        [ "suitableForIppRealFloatVectorReductionOp", "conceptvctr_1_1is_1_1suitableForIppRealFloatVectorReductionOp.html", null ],
        [ "suitableForIppRealOrComplexFloatVectorReductionOp", "conceptvctr_1_1is_1_1suitableForIppRealOrComplexFloatVectorReductionOp.html", null ],
        [ "suitableForBinaryVectorOp", "conceptvctr_1_1is_1_1suitableForBinaryVectorOp.html", null ],
        [ "suitableForAccelerateRealFloatBinaryVectorOp", "conceptvctr_1_1is_1_1suitableForAccelerateRealFloatBinaryVectorOp.html", null ],
        [ "suitableForAccelerateComplexFloatBinaryVectorOp", "conceptvctr_1_1is_1_1suitableForAccelerateComplexFloatBinaryVectorOp.html", null ],
        [ "suitableForAccelerateRealOrComplexComplexFloatBinaryVectorOp", "conceptvctr_1_1is_1_1suitableForAccelerateRealOrComplexComplexFloatBinaryVectorOp.html", null ],
        [ "suitableForIppRealFloatBinaryVectorOp", "conceptvctr_1_1is_1_1suitableForIppRealFloatBinaryVectorOp.html", null ],
        [ "suitableForIppComplexFloatBinaryVectorOp", "conceptvctr_1_1is_1_1suitableForIppComplexFloatBinaryVectorOp.html", null ],
        [ "suitableForIppRealOrComplexComplexFloatBinaryVectorOp", "conceptvctr_1_1is_1_1suitableForIppRealOrComplexComplexFloatBinaryVectorOp.html", null ],
        [ "triviallyCopyableWithDataAndSize", "conceptvctr_1_1is_1_1triviallyCopyableWithDataAndSize.html", null ],
        [ "iteratorCopyable", "conceptvctr_1_1is_1_1iteratorCopyable.html", null ],
        [ "suitableInitializerForElementType", "conceptvctr_1_1is_1_1suitableInitializerForElementType.html", null ],
        [ "suitableInitializerFunction", "conceptvctr_1_1is_1_1suitableInitializerFunction.html", null ],
        [ "suitableInitializerFunctionForElementType", "conceptvctr_1_1is_1_1suitableInitializerFunctionForElementType.html", null ],
        [ "inputIteratorToConstructValuesOfType", "conceptvctr_1_1is_1_1inputIteratorToConstructValuesOfType.html", null ],
        [ "contiguousIteratorWithValueTypeSameAs", "conceptvctr_1_1is_1_1contiguousIteratorWithValueTypeSameAs.html", null ],
        [ "storageInfo", "conceptvctr_1_1is_1_1storageInfo.html", null ],
        [ "reductionExpression", "conceptvctr_1_1is_1_1reductionExpression.html", null ],
        [ "functionWithSignature", "conceptvctr_1_1is_1_1functionWithSignature.html", null ],
        [ "functionWithSignatureOrImplicitlyConvertible", "conceptvctr_1_1is_1_1functionWithSignatureOrImplicitlyConvertible.html", null ],
        [ "triviallyCopyable", "conceptvctr_1_1is_1_1triviallyCopyable.html", null ],
        [ "nonConst", "conceptvctr_1_1is_1_1nonConst.html", null ],
        [ "pointer", "conceptvctr_1_1is_1_1pointer.html", null ],
        [ "noPointer", "conceptvctr_1_1is_1_1noPointer.html", null ],
        [ "uniquePtr", "conceptvctr_1_1is_1_1uniquePtr.html", null ],
        [ "stdTuple", "conceptvctr_1_1is_1_1stdTuple.html", null ],
        [ "stdTupleWithTypes", "conceptvctr_1_1is_1_1stdTupleWithTypes.html", null ],
        [ "constant", "conceptvctr_1_1is_1_1constant.html", null ],
        [ "constantWithType", "conceptvctr_1_1is_1_1constantWithType.html", null ],
        [ "range", "conceptvctr_1_1is_1_1range.html", null ],
        [ "rangeWithValueType", "conceptvctr_1_1is_1_1rangeWithValueType.html", null ],
        [ "number", "conceptvctr_1_1is_1_1number.html", null ],
        [ "intNumber", "conceptvctr_1_1is_1_1intNumber.html", null ],
        [ "int32Number", "conceptvctr_1_1is_1_1int32Number.html", null ],
        [ "int64Number", "conceptvctr_1_1is_1_1int64Number.html", null ],
        [ "signedNumber", "conceptvctr_1_1is_1_1signedNumber.html", null ],
        [ "signedIntNumber", "conceptvctr_1_1is_1_1signedIntNumber.html", null ],
        [ "unsignedIntNumber", "conceptvctr_1_1is_1_1unsignedIntNumber.html", null ],
        [ "realNumber", "conceptvctr_1_1is_1_1realNumber.html", null ],
        [ "realFloatNumber", "conceptvctr_1_1is_1_1realFloatNumber.html", null ],
        [ "complexFloatNumber", "conceptvctr_1_1is_1_1complexFloatNumber.html", null ],
        [ "realOrComplexFloatNumber", "conceptvctr_1_1is_1_1realOrComplexFloatNumber.html", null ],
        [ "disabledConstant", "conceptvctr_1_1is_1_1disabledConstant.html", null ],
        [ "powerOfTwoInt", "conceptvctr_1_1is_1_1powerOfTwoInt.html", null ]
      ] ]
    ] ]
];