var searchData=
[
  ['scalarcompareop_0',['ScalarCompareOp',['../structvctr_1_1ScalarCompareOp.html',1,'vctr']]],
  ['scalarcompareop_3c_20compareop_3a_3aequal_20_3e_1',['ScalarCompareOp&lt; CompareOp::equal &gt;',['../structvctr_1_1ScalarCompareOp_3_01CompareOp_1_1equal_01_4.html',1,'vctr']]],
  ['scalarcompareop_3c_20compareop_3a_3agreater_20_3e_2',['ScalarCompareOp&lt; CompareOp::greater &gt;',['../structvctr_1_1ScalarCompareOp_3_01CompareOp_1_1greater_01_4.html',1,'vctr']]],
  ['scalarcompareop_3c_20compareop_3a_3agreaterorequal_20_3e_3',['ScalarCompareOp&lt; CompareOp::greaterOrEqual &gt;',['../structvctr_1_1ScalarCompareOp_3_01CompareOp_1_1greaterOrEqual_01_4.html',1,'vctr']]],
  ['scalarcompareop_3c_20compareop_3a_3aless_20_3e_4',['ScalarCompareOp&lt; CompareOp::less &gt;',['../structvctr_1_1ScalarCompareOp_3_01CompareOp_1_1less_01_4.html',1,'vctr']]],
  ['scalarcompareop_3c_20compareop_3a_3alessorequal_20_3e_5',['ScalarCompareOp&lt; CompareOp::lessOrEqual &gt;',['../structvctr_1_1ScalarCompareOp_3_01CompareOp_1_1lessOrEqual_01_4.html',1,'vctr']]],
  ['scalarcompareop_3c_20compareop_3a_3anotequal_20_3e_6',['ScalarCompareOp&lt; CompareOp::notEqual &gt;',['../structvctr_1_1ScalarCompareOp_3_01CompareOp_1_1notEqual_01_4.html',1,'vctr']]],
  ['simdregisterunion_7',['SIMDRegisterUnion',['../unionvctr_1_1ExpressionTemplateBase_1_1SIMDRegisterUnion.html',1,'vctr::ExpressionTemplateBase']]],
  ['sin_8',['Sin',['../classvctr_1_1expressions_1_1Sin.html',1,'vctr::expressions']]],
  ['sinh_9',['Sinh',['../classvctr_1_1expressions_1_1Sinh.html',1,'vctr::expressions']]],
  ['span_10',['Span',['../classvctr_1_1Span.html',1,'vctr']]],
  ['sqrt_11',['Sqrt',['../classvctr_1_1expressions_1_1Sqrt.html',1,'vctr::expressions']]],
  ['square_12',['Square',['../classvctr_1_1expressions_1_1Square.html',1,'vctr::expressions']]],
  ['ssefilter_13',['SSEFilter',['../classvctr_1_1expressions_1_1SSEFilter.html',1,'vctr::expressions']]],
  ['sseregister_14',['SSERegister',['../structvctr_1_1SSERegister.html',1,'vctr']]],
  ['sseregister_3c_20typename_20commonsrcelement_3a_3atype_20_3e_15',['SSERegister&lt; typename CommonSrcElement::Type &gt;',['../structvctr_1_1SSERegister.html',1,'vctr']]],
  ['staticstorageinfo_16',['StaticStorageInfo',['../structvctr_1_1StaticStorageInfo.html',1,'vctr']]],
  ['staticstorageinfo_3c_20false_2c_20false_2c_20alignof_28sampletype_29_3e_17',['StaticStorageInfo&lt; false, false, alignof(SampleType)&gt;',['../structvctr_1_1StaticStorageInfo.html',1,'vctr']]],
  ['storageinfo_18',['StorageInfo',['../structvctr_1_1StorageInfo.html',1,'vctr']]],
  ['storageinfo_3c_20detail_3a_3astdvectortype_3c_20elementtype_2c_20defaultvectorallocator_20_3e_20_3e_19',['StorageInfo&lt; detail::StdVectorType&lt; ElementType, DefaultVectorAllocator &gt; &gt;',['../structvctr_1_1StorageInfo.html',1,'vctr']]],
  ['storageinfo_3c_20std_3a_3aarray_3c_20elementtype_2c_20detail_3a_3astorageextent_3c_20elementtype_2c_20extent_20_3e_3a_3aextent_20_3e_20_3e_20',['StorageInfo&lt; std::array&lt; ElementType, detail::StorageExtent&lt; ElementType, extent &gt;::extent &gt; &gt;',['../structvctr_1_1StorageInfo.html',1,'vctr']]],
  ['storageinfo_3c_20std_3a_3aarray_3c_20elementtype_2c_20size_20_3e_20_3e_21',['StorageInfo&lt; std::array&lt; ElementType, size &gt; &gt;',['../structvctr_1_1StorageInfo_3_01std_1_1array_3_01ElementType_00_01size_01_4_01_4.html',1,'vctr']]],
  ['storageinfo_3c_20std_3a_3aarray_3c_20std_3a_3aunique_5fptr_3c_20ownedelementtype_20_3e_2c_20detail_3a_3astorageextent_3c_20std_3a_3aunique_5fptr_3c_20ownedelementtype_20_3e_2c_20extent_20_3e_3a_3aextent_20_3e_20_3e_22',['StorageInfo&lt; std::array&lt; std::unique_ptr&lt; OwnedElementType &gt;, detail::StorageExtent&lt; std::unique_ptr&lt; OwnedElementType &gt;, extent &gt;::extent &gt; &gt;',['../structvctr_1_1StorageInfo.html',1,'vctr']]],
  ['storageinfo_3c_20std_3a_3aspan_3c_20elementtype_2c_20std_3a_3adynamic_5fextent_20_3e_20_3e_23',['StorageInfo&lt; std::span&lt; ElementType, std::dynamic_extent &gt; &gt;',['../structvctr_1_1StorageInfo.html',1,'vctr']]],
  ['storageinfo_3c_20std_3a_3avector_3c_20elementtype_2c_20alignedallocator_3c_20elementtype_2c_20alignmentinbytes_20_3e_20_3e_20_3e_24',['StorageInfo&lt; std::vector&lt; ElementType, AlignedAllocator&lt; ElementType, alignmentInBytes &gt; &gt; &gt;',['../structvctr_1_1StorageInfo_3_01std_1_1vector_3_01ElementType_00_01AlignedAllocator_3_01ElementTypb1ff9125abc35bf2a038ab1c1b675ea6.html',1,'vctr']]],
  ['storageinfo_3c_20storagetype_20_3e_25',['StorageInfo&lt; StorageType &gt;',['../structvctr_1_1StorageInfo_3_01StorageType_01_4.html',1,'vctr']]],
  ['storageinfowithmemberalignment_26',['StorageInfoWithMemberAlignment',['../structvctr_1_1StorageInfoWithMemberAlignment.html',1,'vctr']]],
  ['storageinfowithmemberalignment_3c_20alignof_28std_3a_3aspan_3c_20elementtype_2c_20std_3a_3adynamic_5fextent_20_3e_29_2c_20storageinfo_3c_20std_3a_3aspan_3c_20elementtype_2c_20std_3a_3adynamic_5fextent_20_3e_20_3e_20_3e_27',['StorageInfoWithMemberAlignment&lt; alignof(std::span&lt; ElementType, std::dynamic_extent &gt;), StorageInfo&lt; std::span&lt; ElementType, std::dynamic_extent &gt; &gt; &gt;',['../structvctr_1_1StorageInfoWithMemberAlignment.html',1,'vctr']]],
  ['subtractsinglefromvec_28',['SubtractSingleFromVec',['../classvctr_1_1expressions_1_1SubtractSingleFromVec.html',1,'vctr::expressions']]],
  ['subtractvecfromsingle_29',['SubtractVecFromSingle',['../classvctr_1_1expressions_1_1SubtractVecFromSingle.html',1,'vctr::expressions']]],
  ['subtractvectors_30',['SubtractVectors',['../classvctr_1_1expressions_1_1SubtractVectors.html',1,'vctr::expressions']]],
  ['sum_31',['Sum',['../classvctr_1_1expressions_1_1Sum.html',1,'vctr::expressions']]]
];
