var annotated_dup =
[
    [ "vctr", "namespacevctr.html", [
      [ "expressions", null, [
        [ "Abs", "classvctr_1_1expressions_1_1Abs.html", null ],
        [ "Acos", "classvctr_1_1expressions_1_1Acos.html", null ],
        [ "Acosh", "classvctr_1_1expressions_1_1Acosh.html", null ],
        [ "AddSingleToVec", "classvctr_1_1expressions_1_1AddSingleToVec.html", null ],
        [ "AddVectors", "classvctr_1_1expressions_1_1AddVectors.html", null ],
        [ "Angle", "classvctr_1_1expressions_1_1Angle.html", null ],
        [ "Asin", "classvctr_1_1expressions_1_1Asin.html", null ],
        [ "Asinh", "classvctr_1_1expressions_1_1Asinh.html", null ],
        [ "Atan", "classvctr_1_1expressions_1_1Atan.html", null ],
        [ "Atanh", "classvctr_1_1expressions_1_1Atanh.html", null ],
        [ "AVXFilter", "classvctr_1_1expressions_1_1AVXFilter.html", null ],
        [ "Clamp", "classvctr_1_1expressions_1_1Clamp.html", null ],
        [ "ClampByConstant", "classvctr_1_1expressions_1_1ClampByConstant.html", null ],
        [ "Conjugate", "classvctr_1_1expressions_1_1Conjugate.html", null ],
        [ "Cos", "classvctr_1_1expressions_1_1Cos.html", null ],
        [ "Cosh", "classvctr_1_1expressions_1_1Cosh.html", null ],
        [ "Cube", "classvctr_1_1expressions_1_1Cube.html", null ],
        [ "DivideSingleByVec", "classvctr_1_1expressions_1_1DivideSingleByVec.html", null ],
        [ "DivideVecBySingle", "classvctr_1_1expressions_1_1DivideVecBySingle.html", null ],
        [ "DivideVectors", "classvctr_1_1expressions_1_1DivideVectors.html", null ],
        [ "Exp", "classvctr_1_1expressions_1_1Exp.html", null ],
        [ "Imag", "classvctr_1_1expressions_1_1Imag.html", null ],
        [ "Ln", "classvctr_1_1expressions_1_1Ln.html", null ],
        [ "Log10", "classvctr_1_1expressions_1_1Log10.html", null ],
        [ "Log2", "classvctr_1_1expressions_1_1Log2.html", null ],
        [ "Map", "classvctr_1_1expressions_1_1Map.html", null ],
        [ "MapFrom0To1", "classvctr_1_1expressions_1_1MapFrom0To1.html", null ],
        [ "MapTo0To1", "classvctr_1_1expressions_1_1MapTo0To1.html", null ],
        [ "Max", "classvctr_1_1expressions_1_1Max.html", null ],
        [ "MaxAbs", "classvctr_1_1expressions_1_1MaxAbs.html", null ],
        [ "Mean", "classvctr_1_1expressions_1_1Mean.html", null ],
        [ "MeanSquare", "classvctr_1_1expressions_1_1MeanSquare.html", null ],
        [ "Min", "classvctr_1_1expressions_1_1Min.html", null ],
        [ "MinAbs", "classvctr_1_1expressions_1_1MinAbs.html", null ],
        [ "MultiplyVecByConstant", "classvctr_1_1expressions_1_1MultiplyVecByConstant.html", null ],
        [ "MultiplyVecBySingle", "classvctr_1_1expressions_1_1MultiplyVecBySingle.html", null ],
        [ "MultiplyVectors", "classvctr_1_1expressions_1_1MultiplyVectors.html", null ],
        [ "NeonFilter", "classvctr_1_1expressions_1_1NeonFilter.html", null ],
        [ "NoAccelerationFilter", "classvctr_1_1expressions_1_1NoAccelerationFilter.html", null ],
        [ "NormalizeSum", "classvctr_1_1expressions_1_1NormalizeSum.html", null ],
        [ "PlatformVectorOpsFilter", "classvctr_1_1expressions_1_1PlatformVectorOpsFilter.html", null ],
        [ "PowConstantBase", "classvctr_1_1expressions_1_1PowConstantBase.html", null ],
        [ "PowConstantExponent", "classvctr_1_1expressions_1_1PowConstantExponent.html", null ],
        [ "PowerSpectrum", "classvctr_1_1expressions_1_1PowerSpectrum.html", null ],
        [ "PowSingleBase", "classvctr_1_1expressions_1_1PowSingleBase.html", null ],
        [ "PowSingleExponent", "classvctr_1_1expressions_1_1PowSingleExponent.html", null ],
        [ "PowVectors", "classvctr_1_1expressions_1_1PowVectors.html", null ],
        [ "Real", "classvctr_1_1expressions_1_1Real.html", null ],
        [ "RootMeanSquare", "classvctr_1_1expressions_1_1RootMeanSquare.html", null ],
        [ "Sin", "classvctr_1_1expressions_1_1Sin.html", null ],
        [ "Sinh", "classvctr_1_1expressions_1_1Sinh.html", null ],
        [ "Sqrt", "classvctr_1_1expressions_1_1Sqrt.html", null ],
        [ "Square", "classvctr_1_1expressions_1_1Square.html", null ],
        [ "SSEFilter", "classvctr_1_1expressions_1_1SSEFilter.html", null ],
        [ "SubtractSingleFromVec", "classvctr_1_1expressions_1_1SubtractSingleFromVec.html", null ],
        [ "SubtractVecFromSingle", "classvctr_1_1expressions_1_1SubtractVecFromSingle.html", null ],
        [ "SubtractVectors", "classvctr_1_1expressions_1_1SubtractVectors.html", null ],
        [ "Sum", "classvctr_1_1expressions_1_1Sum.html", null ],
        [ "Tan", "classvctr_1_1expressions_1_1Tan.html", null ],
        [ "Tanh", "classvctr_1_1expressions_1_1Tanh.html", null ],
        [ "TransformedBy", "classvctr_1_1expressions_1_1TransformedBy.html", null ],
        [ "TransformedByStaticCast", "classvctr_1_1expressions_1_1TransformedByStaticCast.html", null ]
      ] ],
      [ "generators", null, [
        [ "Linspace", "structvctr_1_1generators_1_1Linspace.html", "structvctr_1_1generators_1_1Linspace" ]
      ] ],
      [ "AlignedAllocator", "classvctr_1_1AlignedAllocator.html", "classvctr_1_1AlignedAllocator" ],
      [ "Array", "classvctr_1_1Array.html", "classvctr_1_1Array" ],
      [ "AVXRegister", "structvctr_1_1AVXRegister.html", null ],
      [ "CombinedStorageInfo", "structvctr_1_1CombinedStorageInfo.html", null ],
      [ "CombinedStorageInfo< InfoA, InfoB >", "structvctr_1_1CombinedStorageInfo_3_01InfoA_00_01InfoB_01_4.html", null ],
      [ "Config", "structvctr_1_1Config.html", null ],
      [ "Constant", "structvctr_1_1Constant.html", null ],
      [ "dBFS", "structvctr_1_1dBFS.html", null ],
      [ "dBPower", "structvctr_1_1dBPower.html", null ],
      [ "dBVoltage", "structvctr_1_1dBVoltage.html", null ],
      [ "DefaultVectorAllocator", "structvctr_1_1DefaultVectorAllocator.html", null ],
      [ "DefaultVectorAllocator< ElementType >", "structvctr_1_1DefaultVectorAllocator_3_01ElementType_01_4.html", null ],
      [ "DisabledConstant", "structvctr_1_1DisabledConstant.html", "structvctr_1_1DisabledConstant" ],
      [ "ExpressionChainBuilderWithRuntimeArgs", "structvctr_1_1ExpressionChainBuilderWithRuntimeArgs.html", "structvctr_1_1ExpressionChainBuilderWithRuntimeArgs" ],
      [ "ExpressionTemplateBase", "structvctr_1_1ExpressionTemplateBase.html", "structvctr_1_1ExpressionTemplateBase" ],
      [ "NeonRegister", "structvctr_1_1NeonRegister.html", null ],
      [ "OwnedArray", "classvctr_1_1OwnedArray.html", "classvctr_1_1OwnedArray" ],
      [ "OwnedVector", "classvctr_1_1OwnedVector.html", "classvctr_1_1OwnedVector" ],
      [ "Range", "classvctr_1_1Range.html", "classvctr_1_1Range" ],
      [ "ReductionExpression", "classvctr_1_1ReductionExpression.html", "classvctr_1_1ReductionExpression" ],
      [ "RequireConstexpr", "structvctr_1_1RequireConstexpr.html", null ],
      [ "Span", "classvctr_1_1Span.html", "classvctr_1_1Span" ],
      [ "SSERegister", "structvctr_1_1SSERegister.html", null ],
      [ "StaticStorageInfo", "structvctr_1_1StaticStorageInfo.html", null ],
      [ "StorageInfo", "structvctr_1_1StorageInfo.html", null ],
      [ "StorageInfo< std::array< ElementType, size > >", "structvctr_1_1StorageInfo_3_01std_1_1array_3_01ElementType_00_01size_01_4_01_4.html", "structvctr_1_1StorageInfo_3_01std_1_1array_3_01ElementType_00_01size_01_4_01_4" ],
      [ "StorageInfo< std::vector< ElementType, AlignedAllocator< ElementType, alignmentInBytes > > >", "structvctr_1_1StorageInfo_3_01std_1_1vector_3_01ElementType_00_01AlignedAllocator_3_01ElementTypb1ff9125abc35bf2a038ab1c1b675ea6.html", "structvctr_1_1StorageInfo_3_01std_1_1vector_3_01ElementType_00_01AlignedAllocator_3_01ElementTypb1ff9125abc35bf2a038ab1c1b675ea6" ],
      [ "StorageInfo< StorageType >", "structvctr_1_1StorageInfo_3_01StorageType_01_4.html", null ],
      [ "StorageInfoWithMemberAlignment", "structvctr_1_1StorageInfoWithMemberAlignment.html", null ],
      [ "VctrBase", "classvctr_1_1VctrBase.html", "classvctr_1_1VctrBase" ],
      [ "Vector", "classvctr_1_1Vector.html", "classvctr_1_1Vector" ]
    ] ]
];