name: 👷‍ Unit Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [develop]

jobs:
  unit_tests:
    strategy:
      matrix:
        configs:
          # Linux clang 15 runners are temporarily disabled due to installation issues. See https://github.com/sonible/VCTR/issues/86
          # - runner: ubuntu-22.04
          #  cc: clang-15
          #  cxx: clang++-15
          #  ipp: no_ipp

          - runner: ubuntu-24.04
            cc: gcc-13
            cxx: g++-13
            ipp: no_ipp

          # Linux clang 15 runners are temporarily disabled due to installation issues. See https://github.com/sonible/VCTR/issues/86
          # - runner: ubuntu-22.04
          #  cc: clang-15
          #  cxx: clang++-15
          #  ipp: ipp

          - runner: ubuntu-24.04
            cc: gcc-13
            cxx: g++-13
            ipp: ipp

          # MSVC currently fails to compile all the expression test cases: https://github.com/sonible/VCTR/issues/142
          # - runner: windows-2022
          #   cc: cl
          #   cxx: cl
          #   ipp: no_ipp

          - runner: windows-2022
            cc: clang-cl
            cxx: clang-cl
            ipp: no_ipp

          - runner: windows-2022
            cc: clang
            cxx: clang++
            ipp: no_ipp

          #   Not supported yet
          # - runner: windows-2022
          #   cc: gcc
          #   cxx: g++
          #   ipp: no_ipp

          # MSVC currently fails to compile all the expression test cases: https://github.com/sonible/VCTR/issues/142
          # - runner: windows-2022
          #   cc: cl
          #   cxx: cl
          #   ipp: ipp

          - runner: windows-2022
            cc: clang-cl
            cxx: clang-cl
            ipp: ipp

          - runner: windows-2022
            cc: clang
            cxx: clang++
            ipp: ipp

          #   Not supported yet
          # - runner: windows-2022
          #   cc: gcc
          #   cxx: g++
          #   ipp: no_ipp

          # macos-14 and upwards runners are ARM based, therefore no IPP needed here
          - runner: macos-14
            cc: clang
            cxx: clang++
            ipp: no_ipp

          # macos-13 is x86_64
          # Todo: macos-13 runners run into std::pmr related runtime linker problems when building with non-brew llvm
          # Todo: Should actually be $(brew --prefix llvm@15) but actions fails to resolve that when used here
          - runner: macos-13
            cc: /usr/local/opt/llvm@15/bin/clang
            cxx: /usr/local/opt/llvm@15/bin/clang++
            ipp: no_ipp

          - runner: macos-13
            cc: /usr/local/opt/llvm@15/bin/clang
            cxx: /usr/local/opt/llvm@15/bin/clang++
            ipp: ipp

      fail-fast: false

    runs-on: ${{ matrix.configs.runner }}

    steps:

      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: (Linux) Install dependencies
      # Todo: Installing llvm 15 fails at the moment. See https://github.com/sonible/VCTR/issues/86 
      # run: sudo apt-get install ninja-build && wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh 15 all && pip3 install conan
        run: sudo apt-get install ninja-build && pip3 install conan
        if: runner.os == 'Linux'

      - name: (macOS) Install dependencies
        run: brew install ninja z3  && pip3 install conan
        if: runner.os == 'macOS'

      - name: (Windows) Install dependencies
        run: choco install ninja -y && pip3 install conan
        if: runner.os == 'Windows'

      - name: (Windows) Configure dev environment variables
        uses: ilammy/msvc-dev-cmd@v1
        if: runner.os == 'Windows'

      - name: Install IPP
        run: pip3 install ipp-static
        if: matrix.configs.ipp == 'ipp'

      # VCTR_AUTOLINK_IPP uses fake ternary operator
      # More details here: https://github.com/actions/runner/issues/409#issuecomment-752775072
      - name: Configure CMake
        run: cmake . -B build -G Ninja -D CMAKE_BUILD_TYPE=Release -D VCTR_BUILD_TEST=1 -D CMAKE_PROJECT_TOP_LEVEL_INCLUDES=ext/cmake-conan/conan_provider.cmake -D VCTR_AUTOLINK_IPP=${{ matrix.configs.ipp == 'ipp' && '1' || '0' }}
        env:
          CC: ${{ matrix.configs.cc }}
          CXX: ${{ matrix.configs.cxx }}

      - name: Build
        run: cmake --build build/ --target vctr_test

      - name: Change execution permissions if necessary
        run: chmod +x ./build/test/TestMain/vctr_test
        if: runner.os != 'Windows'

      - name: Run test
        run: ./build/test/TestMain/vctr_test
